app:
  applicationId: ${APP_ID:718938fc-0044-476c-b10a-72e180c9c998}
  env: ${APP_ENV:dev-api}
  host: ${APP_HOST:https://localhost:9000}
  excludePaths:
    - "/logout"
  antiCsrfParam: "_csrf"
  authentication:
    loggedInIndicator: "HTTP.*200.*"
    loggedOutIndicator: ".*Location:.*/login.*"
    usernamePassword:
      type: JSON
      loginPath: /api/jwt/auth/signin
      usernameField: username
      passwordField: password
      scanUsername: "user"
      scanPassword: "password"
    tokenAuthorization:
      type: HEADER
      value: Authorization
      tokenType: Bearer
    tokenExtraction:
      type: TOKEN_PATH
      value: "token"
    testPath:
      path: /api/jwt/items/search/i
      success: "HTTP.*200.*"
  openApiConf:
    # path: /openapi
    filePath: openapi.yaml
    fakerEnabled: true #default false
    includeAllMethods: true
    includedMethods:
      - POST
      - PUT
    customVariables:
      - field: text
        values:
          - "$faker:Yoda.quote"
      - field: searchText
        values:
          - "$faker:Crypto.sha512"
      - field: username
        values:
          - "$faker:fullName"
      - field: password
        values:
          - "$faker:password"

#Github PR Comments and UI
tags:
  - name: _STACKHAWK_GIT_COMMIT_SHA
    value: ${COMMIT_SHA:}
  - name: _STACKHAWK_GIT_BRANCH
    value: ${BRANCH_NAME:}